- hosts: tag_three_tier_app_*_bastion
  become: yes
  tasks:
    - name: print host vars
      debug:
        var: hostvars[inventory_hostname]

- hosts: apps
  become: yes
  tags: configure_apps
  roles:
    - role: apps

- hosts: db
  become: yes
  tags: configure_db
  roles:
    - role: appdbs

- hosts: frontends
  become: yes
  tags: configure_frontend
  vars:
    GUID:  "{{ GUID | default(lookup('env','GUID')) or 5414 }}"
  roles:
    - role: frontends

- hosts: jumpbox
  become: yes
  tags: test haproxy
  tasks:
  - name: ensure haproxy is running
    uri:
      url: http://{{item}}/
      status_code: 200
    with_items: "{{groups['frontends']|list}}"
