- hosts: tag_three_tier_app_*_bastion
  become: yes
  tasks:
    - name: get ip for proxy ssh
      debug:
        var: hostvars[inventory_hostname]

- hosts: tag_three_tier_app_*_app
  become: yes
  tags: configure_apps
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q  abashir-redhat.com@bastion.abdd.example.opentlc.com"'
  roles:
    - role: apps

- hosts: tag_three_tier_app_*_appdb
  become: yes
  tags: configure_db
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q  abashir-redhat.com@bastion.abdd.example.opentlc.com"'
  roles:
    - role: appdbs

- hosts: tag_three_tier_app_*_frontend
  become: yes
  tags: configure_frontend
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q  abashir-redhat.com@bastion.abdd.example.opentlc.com"'
    GUID:  "{{ GUID | default(lookup('env','GUID')) or 5414 }}"
  roles:
    - role: frontends

- hosts: tag_three_tier_app_*_bastion
  become: yes
  tags: test haproxy
  tasks:
  - name: ensure haproxy is running
    uri:
      url: http://{{item}}/
      status_code: 200
    with_items: "{{groups['frontends']|list}}"
    delegate_to: tag_three_tier_app_*_bastion
