- hosts: tag_three_tier_app_*_bastion
  become: yes
  tasks:
  - name: get GUID
    shell: hostname | awk -F"." '{print $1}' | awk -F"-" '{print $2}'
    register: guid

  - name: set GUID
    debug:
      msg: "{{guid.stdout}}"

  - name: set fact
    set_fact:
      GUID: "{{guid.stdout}}"

  - name: clone repo
    git:
      repo: 'https://github.com/ahmbas/ansible-course.git'
      dest: /root/ansible-course

  - name: add playbook template
    template:
      src: /root/ansible-course/provision_aws.yaml.j2
      dest: /root/ansible-course/provision_aws_playbook.yaml
      owner: bin
      group: wheel
      mode: 0644

  - name: run playbook
    shell: "ansible-playbook /root/ansible-course/provision_aws_playbook.yaml"
