- hosts: localhost
  tasks:
  - name: trigger update till 3 tier appears
    uri:
      url: https://tower2.7dc9.example.opentlc.com/api/v2/inventories/6/update_inventory_sources/
      method: POST
      user: admin
      password: r3dh4t!
      body_format: json
    until: groups.keys() |  map('regex_search','tag_three_tier_app*') | list


- hosts: tag_three_tier_app_*_bastion
  become: yes
  tasks:
  - name: get GUID
    shell: hostname | awk -F"." '{print $1}' | awk -F"-" '{print $2}'
    register: guid

  - name: set GUID
    debug:
      msg: "{{guid.stdout}}"

  - name: set fact
    set_fact:
      GUID: "{{guid.stdout}}"

  - name: clone repo
    git:
      repo: 'https://github.com/ahmbas/ansible-course.git'
      dest: /root/ansible-course

  - name: add playbook template
    template:
      src: provision_aws.yaml.j2
      dest: /root/ansible-course/provision_aws_playbook.yaml
      owner: root
      group: root
      mode: 0644

  - name: run playbook
    shell: "ansible-playbook /root/ansible-course/provision_aws_playbook.yaml"
