- hosts: localhost
  become: yes
  tasks:
    - name: Get EC2 Facts
      ec2_instance_facts:
        filters:
          "tag:Name": bastion
      register: result

    - name: print ec2
      debug:
        msg: "{{result}}"
