- hosts: jumpbox
  tags: setup flavor
  tasks:
    - name: setup flavor
      os_nova_flavor:
        cloud: ospcloud
        state: present
        name: m2.small
        ram: 2048
        vcpus: 1
        disk: 10

- hosts: jumpbox
  tags: setup security groups
  roles:
    - role: openstack_security_group

- hosts: jumpbox
  tags: setup_networks
  tasks:
    - name: create public network
      os_network:
        cloud: ospcloud
        state: present
        name: ext_network
        external: true

    - name: create public subnet
      os_subnet:
        cloud: ospcloud
        state: present
        network_name: ext_network
        name: public_subnet
        cidr: 10.10.10.0/24
        dns_nameservers:
           - 8.8.8.7
           - 8.8.8.8
        host_routes:
           - destination: 0.0.0.0/0
             nexthop: 10.10.10.0
           - destination: 192.168.0.0/24
             nexthop: 192.168.0.0

    - name: create private network
      os_network:
        cloud: ospcloud
        state: present
        name: private_network
        external: false

    - name: create private subnet
      os_subnet:
        cloud: ospcloud
        state: present
        network_name: private_network
        name: private_subnet
        cidr: 20.20.20.0/24
        dns_nameservers:
           - 8.8.8.8
           - 8.8.8.7
        host_routes:
           - destination: 0.0.0.0/0
             nexthop: 192.168.0.0
           - destination: 192.168.0.0/24
             nexthop: 192.168.0.0

    - name: create router
      os_router:
        cloud: ospcloud
        state: present
        name: router1
        network: ext_network
        external_fixed_ips:
          - subnet: public_subnet
        interfaces:
          - private_subnet

- hosts: jumpbox
  tags: setup_keypair
  tasks:
    - name: add keypair
      os_keypair:
        cloud: ospcloud
        state: present
        name: ansible_ssh
        public_key_file: /root/.ssh/id_rsa.pub

- hosts: jumpbox
  tags: provision instances
  roles:
    - role: openstack_provision_instances
