- hosts: jumpbox
  tags: setup flavor
  tasks:
    - name: setup flavor
      os_nova_flavor:
        cloud: ospcloud
        state: present
        name: m2.small
        ram: 2048
        vcpus: 1
        disk: 10
