- name: refresh inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Refresh EC2 facts
      ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:owner": abashir*
          "tag:Project": three-tier-app-*
      register: result
      until: result.instances != []
      retries: 100
      delay: 60

    - name: trigger update till 3 tier appears
      shell: curl -k -u admin:r3dh4t1! -X POST https://tower2.7dc9.example.opentlc.com/api/v2/inventories/6/update_inventory_sources/
