- name: refresh inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Refresh EC2 facts
      ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:owner": abashir*
          "tag:Project": three-tier-app-*
          "tag:Name": bastion
      register: ec2
      until: ec2.instances != []
      retries: 100
      delay: 60

    - name: de
      debug:
        msg: "{{ec2}}"

    - name: wait for the instances to boot by checking the ssh port
      wait_for: host={{item.public_ip_address}} port=22 delay=60 timeout=320 state=started
      with_items: "{{ec2.instances | list }}"

    - name: trigger update till 3 tier appears
      shell: curl -k -u admin:r3dh4t1! -X POST https://tower2.7dc9.example.opentlc.com/api/v2/inventories/6/update_inventory_sources/
