---
# tasks file for openstack_security_group
- name: create security groups
  os_security_group:
    cloud: ospcloud
    state: present
    name: "{{item.name}}"
    description: "security group for {{item.name}} servers"
  with_items: "{{security_groups}}"

- name: add app security group rules
  os_security_group_rule:
    cloud: ospcloud
    security_group: "app"
    protocol: "{{item['protocol']}}"
    port_range_min: "{{item['port_min']}}"
    port_range_max: "{{item['port_min']}}"
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ app_security_group['rules'] }}"

- name: add db security group rules
  os_security_group_rule:
    cloud: ospcloud
    security_group: "db"
    protocol: "{{item['protocol']}}"
    port_range_min: "{{item['port_min']}}"
    port_range_max: "{{item['port_min']}}"
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ db_security_group['rules'] }}"


- name: add frontend security group rules
  os_security_group_rule:
    cloud: ospcloud
    security_group: "frontend"
    protocol: "{{item['protocol']}}"
    port_range_min: "{{item['port_min']}}"
    port_range_max: "{{item['port_min']}}"
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ frontend_security_group['rules'] }}"
